# Generated by Django 2.2.6 on 2019-12-28 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('schedule_url_slug', models.TextField()),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('race_official', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('team_name', models.TextField()),
                ('driver_url_slug', models.TextField()),
                ('car_number', models.IntegerField()),
                ('car_manuf', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('birthdate', models.DateField()),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drift.League')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('league', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drift.League')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('racers', models.ManyToManyField(to='drift.Racer')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('award', models.TextField(choices=[('win', 'win'), ('qualify', 'quality'), ('qualify-position', 'qualify-position'), ('top-32', 'top-32'), ('top-16', 'top-16'), ('top-8', 'top-8'), ('quarters', 'quarters'), ('final', 'final'), ('podium', 'podium'), ('one-more-time', 'one-more-time'), ('checked-in', 'checked-in'), ('clean-sweep', 'clean-sweep')])),
                ('points', models.IntegerField()),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drift.League')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('rank', models.IntegerField()),
                ('points', models.IntegerField()),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drift.Racer')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('bottom_seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_racer_bottom_seed', to='drift.Racer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drift.Event')),
                ('top_seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_racer_top_seed', to='drift.Racer')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_racer_winner', to='drift.Racer')),
            ],
        ),
        migrations.CreateModel(
            name='Qualify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('rank', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drift.Event')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drift.Racer')),
            ],
        ),
    ]
