# Generated by Django 2.2.6 on 2020-02-25 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0001_squashed_0022_league_key_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(default='2019')),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='league',
            name='key_required',
            field=models.BooleanField(default=True, verbose_name='Require a key to join?'),
        ),
        migrations.AlterField(
            model_name='race',
            name='event_round',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='nonce',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drift.Season'),
        ),
        migrations.AddField(
            model_name='league',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drift.Season'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drift.Season'),
        ),
    ]
