# Generated by Django 2.2.6 on 2019-12-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
    ]
