# Generated by Django 2.2.6 on 2019-12-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0002_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
