# Generated by Django 2.2.6 on 2020-02-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0003_auto_20200225_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='pro2',
            field=models.BooleanField(default=False),
        ),
    ]
