# Generated by Django 2.2.6 on 2019-12-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0003_auto_20191228_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(default='something'),
            preserve_default=False,
        ),
    ]
