# Generated by Django 2.2.6 on 2020-02-25 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0005_qualify_pro2'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualify',
            name='scraped',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 6, 21, 28, 341352)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='scraped',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 6, 21, 38, 817340)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ranking',
            name='scraped',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 6, 21, 51, 133450)),
            preserve_default=False,
        ),
    ]
