# Generated by Django 2.2.6 on 2019-12-29 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0006_auto_20191229_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='bottom_seed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_racer_bottom_seed', to='drift.Racer'),
        ),
    ]
