# Generated by Django 2.2.6 on 2020-02-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0006_auto_20200225_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='racer',
            name='pro2',
            field=models.BooleanField(default=False),
        ),
    ]
