# Generated by Django 2.2.6 on 2019-12-29 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0007_auto_20191229_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='event_round',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='race',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_racer_winner', to='drift.Racer'),
        ),
    ]
