# Generated by Django 2.2.6 on 2020-02-29 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0008_auto_20200228_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverWireRemove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drift.Racer')),
                ('waiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drift.WaiverWire')),
            ],
        ),
    ]
