# Generated by Django 2.2.6 on 2020-03-01 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0009_waiverwireremove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='msg',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_sender', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('proposedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_team_proposedTo', to='drift.Team')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_team_proposer', to='drift.Team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drift.Season')),
            ],
        ),
    ]
