# Generated by Django 2.2.6 on 2020-03-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0010_auto_20200301_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='racerIn',
            field=models.ManyToManyField(related_name='trade_racersIn', to='drift.Racer'),
        ),
        migrations.AddField(
            model_name='trade',
            name='racersOut',
            field=models.ManyToManyField(related_name='trade_racersOut', to='drift.Racer'),
        ),
    ]
