# Generated by Django 2.2.6 on 2020-02-15 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0011_draftdate_draftorder_matchupseed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drift.Event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drift.Team')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drift.ScoringValue')),
            ],
        ),
    ]
