# Generated by Django 2.2.6 on 2020-02-15 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0012_scoringevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringvalue',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drift.League'),
        ),
    ]
