# Generated by Django 2.2.6 on 2020-02-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0015_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='league',
        ),
    ]
