# Generated by Django 2.2.6 on 2020-03-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0015_auto_20200302_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draftpick',
            old_name='draft_order',
            new_name='pick_number',
        ),
        migrations.AddField(
            model_name='draftdate',
            name='one_hour_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='draftpick',
            name='round',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
