# Generated by Django 2.2.6 on 2020-03-06 08:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0016_auto_20200302_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('priority', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=[], size=None)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drift.Team')),
            ],
        ),
    ]
