# Generated by Django 2.2.6 on 2020-02-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0016_remove_userdetail_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='nonce',
            field=models.TextField(null=True),
        ),
    ]
