# Generated by Django 2.2.6 on 2020-02-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0017_userdetail_nonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='nonce',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
