# Generated by Django 2.2.6 on 2020-02-16 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0018_auto_20200216_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='race_official',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
