# Generated by Django 2.2.6 on 2020-03-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0018_auto_20200306_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftdate',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
