# Generated by Django 2.2.6 on 2020-03-10 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0019_draftdate_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPickReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draftpickreservation_draft', to='drift.DraftDate')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drift.DraftDate')),
            ],
        ),
    ]
