# Generated by Django 2.2.6 on 2020-03-10 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0020_draftpickreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpickreservation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drift.Team'),
        ),
    ]
