# Generated by Django 2.2.6 on 2020-03-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0021_auto_20200310_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringvalue',
            name='award',
            field=models.TextField(choices=[('win', 'win'), ('qualify', 'quality'), ('qualify-position', 'qualify-position'), ('top-32', 'top-32'), ('top-16', 'top-16'), ('top-8', 'top-8'), ('quarters', 'quarters'), ('final', 'final'), ('pro2-bonus', 'pro2-bonus')]),
        ),
    ]
