# Generated by Django 2.2.6 on 2020-03-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0022_auto_20200315_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringvalue',
            name='award',
            field=models.TextField(choices=[('win', 'win'), ('qualify', 'qualify'), ('qualify-position', 'qualify-position'), ('top-32', 'top-32'), ('top-16', 'top-16'), ('top-8', 'top-8'), ('quarters', 'quarters'), ('final', 'final'), ('pro2-bonus', 'pro2-bonus')]),
        ),
    ]
