# Generated by Django 2.2.6 on 2020-03-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0023_auto_20200321_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringevent',
            name='team',
        ),
        migrations.AlterField(
            model_name='scoringvalue',
            name='award',
            field=models.TextField(choices=[('win', 'W'), ('qualify', 'Q'), ('qualify-position', 'QP'), ('top-32', 'T32'), ('top-16', 'T16'), ('top-8', 'T8'), ('quarters', 'T4'), ('final', 'T2'), ('pro2-bonus', 'pro2-bonus')]),
        ),
    ]
